# -*- coding: utf-8 -*-
"""[Zero-crossings_in_time_series].model_def.DNN.keras.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1wRnQycHN52WER5IOBU-FGaixXFWaevyQ
"""

import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
import numpy as np
import warnings
from keras.callbacks import EarlyStopping
def compile_model(inp_shape):
    #Create a sequential model
    model = Sequential()
    #Define the number of units in each layer
    n_units = 100
    #Add three dense layers 
    model.add(Dense(n_units,activation = 'tanh',input_shape=[inp_shape]))
    model.add(Dense(n_units,activation = 'tanh'))
    model.add(Dense(n_units,activation = 'tanh'))
    #Add the output layer
    model.add(Dense(1))
    #Compile the model
    model.compile(loss='mean_squared_error', optimizer='adam')
    #Compile the early stopping condition to avoid overfitting
    es = EarlyStopping(monitor='loss', mode='min', verbose=0, patience=5)
    return model,es

